### ISSUE TITLE
Redirect mode supported?

### ISSUE THREAD

**Issue by NoelBaron** [google-pay/google-pay-button#48]
Hi there! Does this button support redirect mode vs. pop-up mode?

This question is related to:

- [x] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)

**Comment by socsieng** [comment]
No, it doesn't. I don't believe Google Pay supports redirect mode.

Can I ask what your use case is?

**Comment by NoelBaron** [comment]
The goal was to support environments where a pop up window spawns a new tab. We'd prefer to interact with google login / pay by leaving the page and redirecting back.

**Comment by socsieng** [comment]
Unfortunately neither the React component or Google Pay support a redirect mode. Note that on supported browsers, the payment handler is used (browser dialogue) instead of popup/tab.

I'm curious to understand if this is show stopper for you.

**Comment by sirikon** [comment]
Hi there, bringing this one up...

I'm working on integrating Google Pay button for a website that needs to support it in as much places as possible. Currently, Google Pay API doesn't report availability (`client.isReadyToPay(...)`) when opened on the Facebook Browser (the browser used inside ads in Facebook App for iOS/Android).

Being able to redirect the user to Google Pay's website and then return it back once the tokenization is completed would be great, because that's the only thing you can do on Facebook's browser, redirect anywhere else. No support for new tabs or popups.

**Comment by dmengelt** [comment]
Hi @sirikon 
Unfortunately this is not possible.
