### ISSUE TITLE
Load pay.js from local file instead of CDN.

### ISSUE THREAD

**Issue by nielsenmg** [google-pay/google-pay-button#81]
Hi everyone,

Due to some compliance requirements we cannot inject remote JS files into our FE app, and this library loads the script `pay.js` file from CDN.

This can be a a very specific requirement that we have, but perhaps other people also have the same requirement, so it would be nice if the library supports loading it from a local file.

In case you don't think this change is suitable for the library, do you have any advices on what we can do to workaround this?

**Comment by socsieng** [comment]
Are you able to elaborate more on the compliance requirements? For example, is it a policy constraint or a technical constraint (e.g. [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP))?

If the problem is related to dynamically injecting JS, you can workaround this by statically loading `https://pay.google.com/gp/p/js/pay.js` into your HTML. Example:

```html
<script async src="https://pay.google.com/gp/p/js/pay.js"></script>
<script async src="app.js"></script>
```

The library won't attempt to inject it [if already loaded](https://github.com/google-pay/google-pay-button/blob/24652d2e17c391402f776e7984dda1e4ce81cc2b/src/lib/button-manager.ts#L78-L80). Example:

```js
if (!this.isGooglePayLoaded()) {
  await loadScript('https://pay.google.com/gp/p/js/pay.js');
}
```

If the problem is something, please elaborate.

**Comment by nielsenmg** [comment]
It's actually PCI compliance, but TBH I'm not really sure if there is an explicit requirement about not loading JS files from external sources, maybe this is something that the team decided by themselves in the past.

Anyway, the solution you proposed did the job, thank you so much!

I'll close the issue!

**Comment by tnishikant** [comment]
I know this is an old thread. Wondering how SRI integrity is calculated on the file hosted by Google, shall we take a local copy? but what happens if Google updates the file?

**Comment by dmengelt** [comment]
@tnishikant A local copy won't work as we generate `pay.js` dynamically. We are currently evaluating potential solutions for for the future...
