### ISSUE TITLE
Button doesn't work when another PaymentRequest UI is open in a different tab

### ISSUE THREAD

**Issue by nielsengoncalves** [google-pay/google-pay-button#88]
Hello,

When there's already a PaymentRequest UI open in a different tab, the Google Pay button doesn't work and it just logs an error in the console.

`Another PaymentRequest UI is already showing in a different tab or window.`

I would like to be able to handle this exception and show some message to the users, however I couldn't find a way yet. I was expecting to be able to use one of the component callbacks such as `onError` to handle that, but apparently this isn't the right way. 

Do you have any advices on how to do that?

Here are the steps to reproduce:

1. Click on google pay button in a tab and leave the PaymentRequest opened
2. Go to a different tab and click the google pay button again.

This question is related to:

- [X] React component (`@google-pay/button-react`)
- [ ] Custom element (`@google-pay/button-element`)
- [ ] Angular component (`@google-pay/button-angular`)

**Comment by socsieng** [comment]
The way this is currently treated is a *cancellation* rather than an error.

You can handle this by supplying an `onCancel` callback. `onCancel` will be invoked both in this scenario and if the user chooses not to proceed with the payment.

Example:

```jsx
<GooglePayButton
  {/* ... */}
  onCancel={response => {
    if (response.message === 'Another PaymentRequest UI is already showing in a different tab or window.') {
      console.log('Handle PaymentRequest UI already showing');
    }
  }}
/>
```

Note that I think the `message` is returned by the browser (i.e. Chrome) rather than the Google Pay API, so you may need to test with other browsers that support the PaymentRequest API as they may return different messages.

I wish there was a better alternative for you at the moment than having to do a string comparison against `message` as this is somewhat brittle, but it's probably the easiest way to accomplish what you are after at the moment.

**Comment by nielsengoncalves** [comment]
Hi @socsieng, 

Thanks for the hint.

I agree with you that doing string comparison for that is not ideal, but anyways we ended up implementing the way you mentioned. For us, it's better to have that than nothing.

I hope in the future there is a better way of handling this error.
